CREATE TABLE todos
(
    id binary(16) generated by default as identity,
    content varchar(100) NOT NULL,
    PRIMARY KEY (id)
);

//Create
INSERT INTO todos ( id, content ) values ( {id}, {content} );

//Read All
SELECT id, content FROM todos;

//Read Single
SELECT id, content
FROM todos
WHERE id = {value};

SELECT id, content
FROM todos
WHERE content = {value};

//Update
UPDATE content
FROM todos
WHERE content = {value};

//Delete
DELETE contant
FROM todos
WHERE content = {value}